# Netlify Configuration File

[build]
  # Directory to build
  base = ""
  
  # Build command
  command = "npm run build"
  
  # Directory that contains the deploy-ready files
  publish = "dist"

[build.environment]
  # Node version for builds
  NODE_VERSION = "20"
  # Vite needs this for proper builds
  VITE_CJS_TRACE = "true"

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Handle client-side routing for React SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Redirect www to non-www (optional - remove if not using custom domain)
[[redirects]]
  from = "https://www.contractoredu.com/*"
  to = "https://contractoredu.com/:splat"
  status = 301
  force = true

# Dev environment settings
[dev]
  command = "npm run dev"
  port = 5173
  targetPort = 5173
  autoLaunch = false